config/routes.rb
Shotweb::Application.routes.draw do
  resources :years, :only => [:index, :show]
  resources :events, :only => [:show]
  match "events/:id/:photo_nbr" => "events#photo", :as => :event_photo
  resources :tags, :only => [:index, :show]
  match "tags/:id/:photo_nbr" => "tags#photo", :as => :tag_photo
  match "photos/:id/:size.jpg" => "photos#thumb", :as => :thumb, :defaults => { :format => 'jpg' }
  match "photos/:id.jpg" => "photos#photo", :as => :photo, :defaults => { :format => 'jpg' }
  root :to => 'years#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  set_table_name :EventTable
  has_many :photos
  
  def primary_source
    Photo.find(Integer("0x" + primary_source_id.split("thumb")[1])) || photos.first
  end
  
  def name
    if read_attribute(:name)
      read_attribute(:name)
    else
      start_date.strftime('%F')
    end
  end
  
  def start_date
    if photos.first.nil? # todo
      Time.at(0)
    else
      Time.at(photos.first.exposure_time)      
    end
  end
  
  def end_date
    if photos.last.nil?
      Time.at(0)
    else
      Time.at(photos.last.exposure_time)
    end
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  set_table_name :PhotoTable
  belongs_to :event
  default_scope order('exposure_time')
  default_scope :conditions => 'rating <> -1' # Skip rating = denied
  default_scope :conditions => 'flags = 0' # Skip flagged photos
  default_scope :conditions => 'event_id <> -1' # Skip photos in trash can
  default_scope :conditions => ['id not in (?)', Tag.find_by_name("Hidden").photos_ids] # Skip photos with "Hidden" tag
  
  def tags
    Tag.all.select do |tag|
      tag.photos_ids.include? id 
    end
  end
  
  def date
    Time.at(exposure_time)      
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  set_table_name :TagTable
  default_scope order('name')
  default_scope :conditions => 'photo_id_list is not null'
  
  def photos_ids
    photo_id_list.split(",").select { |t| t.include? "thumb"}.collect do |id|
      Integer("0x" + id.split("thumb")[1])
    end
  end

  def nbr_photos
    Photo.count(:all, :conditions => ['id in (?)', photos_ids]) # todo count much faster than find, could this extra method be avoided?    
  end

  def photos
    Photo.all(:conditions => ['id in (?)', photos_ids]).reverse # todo find(photos_ids) doesn't work, photo.rb filters some ids...
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time

  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def show
    @event = Event.find(params[:id])
    @photos = @event.photos.paginate :page => params[:page], :per_page => 9
  end
  
  def photo
    @event = Event.find(params[:id])
    @index = params[:photo_nbr].to_i
    @last_index = @event.photos.length
    @page = (@index - 1) / 9 + 1
    @photo = @event.photos[@index - 1]
    render :action => "photos/show"
  end
  
end

app/controllers/photos_controller.rb
require 'RMagick'

class PhotosController < ApplicationController
  caches_page :thumb
  include Magick

  def thumb
    if ["100","200","400","800"].include?(params[:size])
      image = ImageList.new(Photo.find(params[:id]).filename)
      image.auto_orient!
      scale_factor = params[:size].to_f / [image.columns, image.rows].max
      if scale_factor < 0.2
        image = image.thumbnail(scale_factor)
      else
        image = image.resize(scale_factor)
      end
      send_data image.to_blob, :type => :jpg, :disposition => "inline"
    end
  end

  def photo
    image = ImageList.new(Photo.find(params[:id]).filename)
    send_data image.auto_orient.to_blob, :type => :jpg, :disposition => "inline"
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @photos = @tag.photos.paginate :page => params[:page], :per_page => 9
  end

  def photo
    @tag = Tag.find(params[:id])
    @index = params[:photo_nbr].to_i
    @last_index = @tag.photos.length
    @page = (@index - 1) / 9 + 1
    @photo = @tag.photos[@index - 1]
    render :action => "photos/show"
  end

end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  def index
    #@years = Event.all.sort_by { |e| e.start_date }.group_by{ |e| e.start_date.year }
    @years = Event.all.select { |e| !e.photos.first.nil?}.sort_by { |e| e.start_date }.reverse.group_by{ |e| e.start_date.year }
  end
  
  def show
    @year = params[:id]
    @events = index[@year.to_i]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def date_interval(start_date, end_date)
    if start_date.year == end_date.year
      if start_date.month == end_date.month
        if start_date.day == end_date.day
          start_date.strftime('%b %e')
        else
          start_date.strftime('%b %e') + end_date.strftime(' - %e')
        end
      else
          start_date.strftime('%b %e') + end_date.strftime(' - %b %e')        
      end
    else
      start_date.strftime('%F') + end_date.strftime(' - %F')
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
  
  def get_photo_path(index)
    if @tag
      tag_photo_path(@tag, index)
    elsif @event
      event_photo_path(@event, index)
    end
  end
  
  def get_parent_path(querystring=nil)
    if @tag
      tag_path(@tag, querystring)
    elsif @event
      event_path(@event, querystring)
    end    
  end

  def get_parent_name
    if @tag
      @tag.name
    elsif @event
      @event.name
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/events/_event.html.erb
<li>
  <%= link_to '<div class="ev">'.html_safe + image_tag(thumb_path(event.primary_source, :size => 200)) + '</div>'.html_safe +
	event.name + 
	'<br/>('.html_safe + pluralize(event.photos.length, 'photo') + ')<br/>'.html_safe + 
	date_interval(event.start_date, event.end_date), event_path(event) %>
</li>

app/views/events/show.html.erb
<div id="header">
  <h1><%= h(@event.name + " (" + @photos.current_page.to_s + "/" + @photos.total_pages.to_s + ")" ) %></h1>
</div>

<div id="content">
<%= will_paginate @photos, :previous_label => "<", :next_label => ">", :page_links => false %>
<ul class="photos">
  <%= render @photos %>
</ul>

  <ul class="list">
    <li><%= link_to h('Up'), year_path(@event.start_date.year) %></li>
    <li><%= link_to h('Top'), years_path %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=APP_CONFIG['title']%></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <meta name="viewport" content="width=device-width" />
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_photo.html.erb
<li>
  <%= link_to image_tag(thumb_path(photo, :size => 200)), get_photo_path(@photos.offset + photo_counter + 1)%>
</li>

app/views/photos/show.html.erb
<div id="header">
  <h1><%= h( get_parent_name + " (" + @index.to_s + "/" + @last_index.to_s + ")" ) %></h1>
</div>

<div id="content">
  <div class="pagination">
	
	<%= if @index > 1
			link_to h("<"), get_photo_path(@index-1), :class => "previous_page" 
		else
			'<span class="previous_page disabled"><</span>'.html_safe
		end %>
	<%= if @index < @last_index
			link_to h(">"), get_photo_path(@index+1), :class => "next_page"
		else
			'<span class="next_page disabled">></span>'.html_safe
		end %>

  </div>
  <p>
    <%= image_tag photo_path(@photo) %>
  </p>

<p>
  <b>Event:</b>
  <%= link_to h(@photo.event.name), event_path(@photo.event) %>
</p>

<p>
  <b>Tags:</b>
  <% @photo.tags.each do |tag| %>
    <%= link_to h(tag.name), tag_path(tag) %>
  <% end %>
</p>

  <ul class="list">
    <li><%= link_to h('Up'), get_parent_path(:page => @page) %></li>
    <li><%= link_to h('Top'), years_path %></li>
  </ul>
</div>

app/views/tags/index.html.erb
<div id="header">
  <h1>Tags</h1>
</div>

<div id="content">
  <ul class="list">
    <% @tags.each do |tag| %>
      <li><%= link_to h(tag.name + " (" + pluralize(tag.nbr_photos, "photo") + ")"), tag_path(tag) %></li>
    <% end %>
  </ul>
  <ul class="list">
    <li><%= link_to h('Up'), years_path %></li>
  </ul>
</div>

app/views/tags/show.html.erb
<div id="header">
  <h1><%= h( @tag.name + " (" + @photos.current_page.to_s + "/" + @photos.total_pages.to_s + ")" ) %></h1>
</div>

<div id="content">
<%= will_paginate @photos, :previous_label => "<", :next_label => ">", :page_links => false %>

<ul class="photos">
  <%= render @photos %>
</ul>

  <ul class="list">
    <li><%= link_to h('All tags'), tags_path %></li>
    <li><%= link_to h('Top'), years_path %></li>
  </ul>
</div>

app/views/years/index.html.erb
<div id="header">
  <h1><%=APP_CONFIG['title']%></h1>
</div>

<div id="content">
  <ul class="list">
    <% @years.each do |year, events| %>
      <li>
		<%= link_to '<div class="ev">'.html_safe + image_tag(thumb_path(events.first.primary_source, :size => 200)) + '</div>'.html_safe +
	        year.to_s + '<br/>('.html_safe + pluralize(events.length, 'event') + ')<br/>'.html_safe, year_path(year) %>
      </li>
    <% end %>
  </ul>
  <ul class="list">
    <li><%= link_to h('Tag list'), tags_path %></li>
  </ul>
</div>

app/views/years/show.html.erb
<div id="header">
  <h1><%= h(@year) %></h1>
</div>

<div id="content">
  <ul class="list">
    <%= render @events %>
  </ul>

  <ul class="list">
    <li><%= link_to h('Up'), years_path %></li>
    <li><%= link_to h('Tag list'), tags_path %></li>
  </ul>
</div>